### ISSUE TITLE
Codeigniter4 Setup instruction is missed

### ISSUE THREAD

**Issue by goeko** [grimpirate/halberd#1]
The project is interesting and I have tried to implement it in a Codeigniter4 project where codeigniter4/shield is setup.

Unfortunately the installation description is incomplete, because there is no information about which adjustments are necessary to set up grimpirate/halberd after the composer installation.

Can the readme please be supplemented with the **necessary steps for a standard shield + halberd setup**?

**Comment by grimpirate** [comment]
No adjustments are required after the composer installation (except for the item listed under the Configuration section). If you correctly set up CodeIgniter and Shield then Halberd should just work out of the box. Perhaps you can elaborate on what isn't working for you?

**Comment by grimpirate** [comment]
The src/Config/Registrar.php file automatically tries to configure what the Shield [documentation suggests](https://shield.codeigniter.com/references/authentication/auth_actions/#configuring-actions). It's possible that if your application already exists it may be defining its own Auth Actions in a Config somewhere at the app level which may be overriding Halberd's configuration.

You can try copying the Registrar.php file's content into the app level Registrar.php, or modify the Auth config file directly to use the classes Halberd provides as shown in the Shield doc linked above.
